### ISSUE TITLE
AttributeError: type object 'OneHotCategorical' has no attribute 'reduce'

### ISSUE THREAD

**Issue by pyrito** [orybkin/video-gcp#14]
Hi guys,

I'm trying to run the model out of the box. I'm following pretty much everything you guys stated in the instructions including this command line:
```
python prediction/train.py --path=../experiments/prediction/25room/gcp_tree/ --skip_first_val=1
```

I'm getting this in my output:
```
Using 2 GPUs!

loading files from ./data/nav_25rooms
setting param n_rooms to value 25
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
len train dataset 23528
loading files from ./data/nav_25rooms
setting param n_rooms to value 25
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
len val dataset 143
Loading from: ./experiment_logs/prediction/25room/gcp_tree/weights
Warning: No checkpoints found at ./experiment_logs/prediction/25room/gcp_tree/weights!
starting epoch  0
Traceback (most recent call last):
  File "/home/vkarthik/video-gcp/blox/torch/training.py", line 109, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: zip argument #1 must support iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prediction/train.py", line 239, in <module>
    trainer.run()
  File "prediction/train.py", line 52, in run
    self.train(start_epoch)
  File "prediction/train.py", line 107, in train
    self.train_epoch(epoch)
  File "prediction/train.py", line 157, in train_epoch
    output = self.model(inputs)
  File "/home/vkarthik/miniconda3/envs/robotlearning/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vkarthik/miniconda3/envs/robotlearning/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/home/vkarthik/video-gcp/blox/torch/training.py", line 89, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/vkarthik/video-gcp/blox/torch/training.py", line 116, in gather
    return gather_map(outputs)
  File "/home/vkarthik/video-gcp/blox/torch/training.py", line 107, in gather_map
    for k in out))
  File "/home/vkarthik/video-gcp/blox/torch/training.py", line 107, in <genexpr>
    for k in out))
  File "/home/vkarthik/video-gcp/blox/torch/training.py", line 111, in gather_map
    return type(out).reduce(*outputs)
AttributeError: type object 'OneHotCategorical' has no attribute 'reduce'
```

Any ideas?

**Comment by pyrito** [comment]
I think I may have figured it out. The GPUs on my machine were a little wonky and after turning that off, things seem to be training now. The error didn't seem quite clear in that regard.

**Comment by orybkin** [comment]
Great, closing for now then!
